import { useEffect, useState } from 'react';

interface LandingProps {
  onOpen: () => void;
}

interface Stats {
  venues: number;
  byType: Record<string, number>;
  routes: number;
  demSamples: number;
  transect: number[];
  transectLabel: string;
}

/**
 * Landing page.
 *
 * One column, left-aligned, on a fixed type and spacing scale. Everything on it
 * is either a real number or a real measurement — the figures and the terrain
 * profile are both generated by build_data.py, so the page cannot drift out of
 * step with the data behind it.
 *
 * The map bundle is code-split, so this renders without downloading MapLibre;
 * the button below is what pulls it in.
 */
export function Landing({ onOpen }: LandingProps) {
  const [stats, setStats] = useState<Stats | null>(null);

  useEffect(() => {
    // A few hundred bytes. The page is complete without it, so a failure here
    // costs nothing but the numbers.
    fetch('data/stats.json')
      .then((r) => (r.ok ? r.json() : null))
      .then(setStats)
      .catch(() => undefined);
  }, []);

  return (
    <div className="landing">
      <div className="shell">
        <header className="lp-nav">
          <span className="wordmark">
            hill<span className="dot">GPX</span>
          </span>
          <a href="https://github.com/StarlightsJourney/HillGPX" target="_blank" rel="noreferrer">
            GitHub
          </a>
        </header>
      </div>

      <main>
        <div className="shell">
          <section className="lp-hero">
            <h1>Find the climb.</h1>
            <p className="lp-lede">
              Every hill, staircase and tall HDB block in Singapore, measured for the climbing it
              actually offers.
            </p>
            <div className="lp-actions">
              <button className="cta" onClick={onOpen}>
                Open the map
              </button>
              <a className="lp-secondary" href="#how">
                How it works
              </a>
            </div>
          </section>
        </div>

        <Transect stats={stats} />

        <div className="shell">
          <section className="lp-stats" aria-label="Dataset size">
            <Figure value={stats ? formatCount(stats.venues) : '—'} label="venues mapped" />
            <Figure value={stats ? formatCount(stats.demSamples) : '—'} label="terrain samples" />
            <Figure value={stats ? String(stats.routes) : '—'} label="routes" />
            <Figure value="0" label="accounts needed" />
          </section>

          <section className="lp-points" id="how">
            <div className="lp-point">
              <h2>Real elevation</h2>
              <p>
                Profiles are computed against a bundled terrain model, not the altitude your watch
                recorded. GPS altitude is noisy enough to invent hundreds of metres of climbing.
              </p>
            </div>
            <div className="lp-point">
              <h2>Nothing is uploaded</h2>
              <p>
                A GPX you open is parsed in this tab and stays there. There is no account, no
                database, and no server to send it to.
              </p>
            </div>
            <div className="lp-point">
              <h2>Open data</h2>
              <p>
                Every venue and route is a file in the repository. A wrong height is a one-line pull
                request, and adding a route is one GPX.
              </p>
            </div>
          </section>
        </div>
      </main>

      <div className="shell">
        <footer className="lp-foot small muted">
          <span>
            Open source, MIT ·{' '}
            <a href="https://data.gov.sg" target="_blank" rel="noreferrer">
              data.gov.sg
            </a>{' '}
            ·{' '}
            <a href="https://openfreemap.org/" target="_blank" rel="noreferrer">
              OpenFreeMap
            </a>{' '}
            ·{' '}
            <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">
              OpenStreetMap
            </a>
          </span>
        </footer>
      </div>
    </div>
  );
}

function Figure({ value, label }: { value: string; label: string }) {
  return (
    <div className="lp-figure">
      <span className="lp-figure-value">{value}</span>
      <span className="lp-figure-label">{label}</span>
    </div>
  );
}

function formatCount(n: number): string {
  return n.toLocaleString('en-SG');
}

/**
 * The real skyline of Singapore's terrain — for each step west to east, the
 * highest ground in the latitude band, sampled from the same model the app uses
 * for elevation profiles. It is the product's own output rather than an
 * illustration, which is the only reason it earns the space.
 */
function Transect({ stats }: { stats: Stats | null }) {
  const points = stats?.transect ?? [];
  // Reserve the space up front so the page does not jump when stats arrive.
  if (points.length < 2) return <div className="lp-transect" aria-hidden="true" />;

  const W = 1000;
  const H = 150;
  const peak = Math.max(...points, 1);
  // Headroom so the summit does not touch the top edge.
  const scale = H / (peak * 1.12);

  const coords = points.map((v, i) => {
    const x = (i / (points.length - 1)) * W;
    const y = H - v * scale;
    return `${x.toFixed(1)} ${y.toFixed(1)}`;
  });

  const line = `M${coords.join(' L')}`;
  const area = `${line} L${W} ${H} L0 ${H} Z`;

  const peakIndex = points.indexOf(peak);
  const peakX = (peakIndex / (points.length - 1)) * W;
  const peakY = H - peak * scale;

  return (
    <figure className="lp-transect">
      <svg
        viewBox={`0 0 ${W} ${H}`}
        preserveAspectRatio="none"
        role="img"
        aria-label={stats!.transectLabel}
      >
        <path d={area} className="transect-fill" />
        <path d={line} className="transect-line" vectorEffect="non-scaling-stroke" />
        <line
          x1={peakX}
          y1={peakY}
          x2={peakX}
          y2={H}
          className="transect-peak"
          vectorEffect="non-scaling-stroke"
        />
      </svg>
      <figcaption className="small muted">
        {stats!.transectLabel}, peaking at {peak} m
      </figcaption>
    </figure>
  );
}
